# Generated by Django 2.2.2 on 2019-06-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome do Cliente')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobernome')),
                ('endereco', models.TextField(verbose_name='Endereço completo')),
            ],
        ),
    ]
