# Generated by Django 2.2.2 on 2019-06-12 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(blank=True, null=True, verbose_name='Serial')),
                ('fabricante', models.CharField(max_length=20, verbose_name='Fabricante')),
                ('modelo', models.CharField(max_length=20, verbose_name='Modelo')),
                ('numportas', models.IntegerField(verbose_name='Número de Portas')),
                ('ip', models.IntegerField(verbose_name='Número do IP')),
                ('mac', models.IntegerField(verbose_name='Número do MAC')),
                ('login', models.CharField(max_length=20, verbose_name='Login')),
                ('senha', models.CharField(max_length=30, verbose_name='Senha')),
            ],
            options={
                'verbose_name_plural': 'Ativos',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Tipo do equipamento')),
            ],
            options={
                'verbose_name_plural': 'Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='Porta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porta', models.IntegerField(verbose_name='Número de Porta')),
                ('idvlan', models.CharField(max_length=10, verbose_name='ID da vlan')),
                ('vlan', models.CharField(max_length=15, verbose_name='Nome da vlan')),
                ('tag', models.CharField(max_length=20, verbose_name='Vlan TAG')),
                ('idponto', models.CharField(blank=True, max_length=20, null=True, verbose_name='ID ponto')),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Ativo', verbose_name='Tipo de Ativo')),
            ],
            options={
                'verbose_name_plural': 'Portas',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome do Setor')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla do Setor')),
            ],
            options={
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Setor', verbose_name='Localização'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Setor', verbose_name='Localização'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Equipamento', verbose_name='Tipo de Equipamento'),
        ),
    ]
