# Generated by Django 2.2.2 on 2019-06-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190612_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='mac',
            field=models.CharField(max_length=25, verbose_name='Número do MAC'),
        ),
    ]
