# Generated by Django 2.2.2 on 2019-06-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190612_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='serial',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Serial'),
        ),
    ]
