# Generated by Django 2.2.2 on 2019-06-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190612_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='ip',
            field=models.CharField(max_length=18, verbose_name='Número do IP'),
        ),
    ]
