# Generated by Django 2.2.2 on 2019-06-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190613_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porta',
            name='id',
        ),
        migrations.AlterField(
            model_name='porta',
            name='porta',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Número de Porta'),
        ),
    ]
