# Generated by Django 2.2.2 on 2019-06-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190613_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ativo',
            name='ip',
            field=models.CharField(max_length=18, verbose_name='Número do IP'),
        ),
    ]
